Repository SUSE/doc-susemanager, pull requests merged in 2019-04, with the labels that each got.

#416 No registration code required for SLE15SP1 and SUSE Manager 4.0
  modules/installation/pages/general-requirements.adoc
Labels: Version 4.0, enhancement

#415 Fix versions for SLE/openSUSE/salt
  branding/pdf-resources/entities.adoc
  suma-site.yml
  uyuni-site.yml
Labels: Version 4.0, bug

#425 updated makefile for uyuni/suma targets
  Makefile
  antora.yml
  suma-site.yml
  uyuni-site.yml
Labels: enhancement, help wanted

#428 added missing user menu content
  modules/reference/assets/images/users_all_users.png
  modules/reference/assets/images/users_deactivated_user_list.png
  modules/reference/assets/images/users_details_addresses.png
  modules/reference/assets/images/users_details_preferences.png
  modules/reference/assets/images/users_details_system_groups.png
  modules/reference/assets/images/users_details_systems.png
  modules/reference/assets/images/users_system_group_config.png
  modules/reference/assets/images/users_system_group_config_external_auth.png
  modules/reference/assets/images/users_user_details.png
  modules/reference/assets/images/users_user_list.png
  modules/reference/nav-reference-manual.adoc
  modules/reference/pages/users/active-users.adoc
  modules/reference/pages/users/all-users.adoc
  modules/reference/pages/users/deactivated-users.adoc
  modules/reference/pages/users/system-group-configuration.adoc
  modules/reference/pages/users/user-details.adoc
  modules/reference/pages/users/users-list.adoc
  modules/reference/pages/users/users-menu.adoc
Labels: enhancement, ia-rework
